import { Box } from "@/components/Box";
import { Suspense } from "react";

export const metadata = {
    title: 'sstore | Доставка',
    description: 'Generated by Next.js',
  };
  
  export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
    return (
      <main className="min-h-screen bg-[#F4F1EE] dark:bg-neutral-900">
        <Box>
          <Suspense>
            <h1 className="border-b-gray-200 dark:bg-neutral-900 dark:border-b-neutral-900
            "
             >
                хедер
             </h1>
          </Suspense>
          {children}
        </Box>
      </main>
    )}
  